site_name: Timpview Voices

theme:
        name: material
        icon:
                logo: fontawesome/solid/mountain
        favicon: img/favicon-16x16.png
        palette:
                primary: light blue
                scheme: default
                accent: cyan
        features:
                - navigation.instant
                - navigation.expand

markdown_extensions:
        - admonition
        - meta
        - attr_list
        - pymdownx.emoji:
                emoji_index: !!python/name:materialx.emoji.twemoji
                emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
        - Home: 'index.md'
        - Suggest a Guest: 'contact.md'
        - Past Guests:
                - Mary Bekker: 'guests/mary-bekker.md'
                - Kaylee Bullock: 'guests/kaylee-bullock.md'
                - Aaron Summerill: 'guests/aaron-summerill.md'
                - Jack Lott: 'guests/jack-lott.md'
                - Chalon Hutson: 'guests/chalon-hutson.md'
                - Rebecca Pickett (Co-Host): 'guests/rebecca-pickett.md'
                - Billy Wilson (Co-Host): 'guests/billy-wilson.md'

extra:
        social:
                - icon: fontawesome/brands/facebook
                  link: https://facebook.com/TimpviewVoices
                  name: Timpview Voices on Facebook
                - icon: fontawesome/brands/twitter
                  link: https://twitter.com/timpviewv
                  name: Timpview Voices on Twitter

extra_css:
        - css/extra.css

copyright: Copyright &copy; 2021 Billy Wilson
